# fly.toml app configuration file generated for proud-waterfall-3971 on 2023-04-28T10:54:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-waterfall-3971"
primary_region = "mia"

[build]
  dockerfile = "./apps/backend/Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  http_checks = []
